class Geoadmin1 < ActiveRecord::Base
  belongs_to :geocountry, :foreign_key=>:country_code, :primary_key=>:iso
  has_many :geoadmin2s, :foreign_key=>:admin1uniq, :primary_key=>:admin1uniq

  def self.findornot(id)
    id = id.to_i
    return nil if id<=0
    begin
      rec = find(id)
    rescue
    end  
    if rec
      return rec
    else
      return nil
    end        
  end  

  def timezone
    #-- Look up what the timezone based on state and region
    case country_code 
    when "US"
      case admin1_code   
      when "AL"
        "America/Chicago"    
      when "AK"
        "America/Anchorage"    
      when "AZ"
        "America/Phoenix"    
      when "AR"
        "America/Chicago"    
      when "CA"
        "America/Los_Angeles"    
      when "CO"
        "America/Denver"    
      when "CT"
        "America/New_York"    
      when "DE"
        "America/New_York"    
      when "DC"
        "America/New_York"    
      when "FL"
        "America/New_York"    
      when "GA"
        "America/New_York"    
      when "HI"
        "Pacific/Honolulu"    
      when "ID"
        "America/Denver"    
      when "IL"
        "America/Chicago"    
      when "IN"
        "America/Indianapolis"    
      when "IA"
        "America/Chicago"    
      when "KS"
        "America/Chicago"    
      when "KY"
        "America/New_York"    
      when "LA"
        "America/Chicago"    
      when "ME"
        "America/New_York"    
      when "MD"
        "America/New_York"    
      when "MA"
        "America/New_York"    
      when "MI"
        "America/New_York"    
      when "MN"
        "America/Chicago"    
      when "MS"
        "America/Chicago"    
      when "MO"
        "America/Chicago"    
      when "MT"
        "America/Denver"    
      when "NE"
        "America/Chicago"    
      when "NV"
        "America/Los_Angeles"    
      when "NH"
        "America/New_York"    
      when "NJ"
        "America/New_York"    
      when "NM"
        "America/Denver"    
      when "NY"
        "America/New_York"    
      when "NC"
        "America/New_York"    
      when "ND"
        "America/Chicago"    
      when "OH"
        "America/New_York"    
      when "OK"
        "America/Chicago"    
      when "OR"
        "America/Los_Angeles"    
      when "PA"
        "America/New_York"    
      when "RI"
        "America/New_York"    
      when "SC"
        "America/New_York"    
      when "SD"
        "America/Chicago"    
      when "TN"
        "America/Chicago"    
      when "TX"
        "America/Chicago"    
      when "UT"
        "America/Denver"    
      when "VT"
        "America/New_York"    
      when "VA"
        "America/New_York"    
      when "WA"
        "America/Los_Angeles"    
      when "WV"
        "America/New_York"    
      when "WI"
        "America/Chicago"    
      when "WY"
        "America/Denver"
      end
    when "CA"
      # ca_conv = {'AB'=>'01', 'BC'=>'02', 'MB'=>'03', 'NB'=>'04', 'NL'=>'05', 'NS'=>'07', 'ON'=>'08', 'PE'=>'09', 'QC'=>'10', 'SK'=>'11', 'YT'=>'12', 'NT'=>'13', 'NU'=>'14'}
      case admin1_code   
      when "01"
        "America/Edmonton"    
      when "02"
        "America/Vancouver"    
      when "03"
        "America/Winnipeg"    
      when "04"
        "America/Halifax"    
      when "05"
        "America/St_Johns"    
      when "13"
        "America/Yellowknife"    
      when "07"
        "America/Halifax"    
      when "14"
        "America/Rankin_Inlet"    
      when "08"
        "America/Rainy_River"    
      when "09"
        "America/Halifax"    
      when "10"
        "America/Montreal"    
      when "11"
        "America/Regina"    
      when "12"
        "America/Whitehorse"
      end 
    when "AU"
      case admin1_code   
      when "01"
        "Australia/Canberra"    
      when "02"
        "Australia/NSW"    
      when "03"
        "Australia/North"    
      when "04"
        "Australia/Queensland"    
      when "05"
        "Australia/South"    
      when "06"
        "Australia/Tasmania"    
      when "07"
        "Australia/Victoria"    
      when "08"
        "Australia/West"
      end
    when "AS"
      "US/Samoa"
    when "CI"
      "Africa/Abidjan"
    when "GH"
      "Africa/Accra"
    when "DZ"
      "Africa/Algiers"
    when "ER"
      "Africa/Asmera"
    when "ML"
      "Africa/Bamako"
    when "CF"
      "Africa/Bangui"
    when "GM"
      "Africa/Banjul"
    when "GW"
      "Africa/Bissau"
    when "CG"
      "Africa/Brazzaville"
    when "BI"
      "Africa/Bujumbura"
    when "EG"
      "Africa/Cairo"
    when "MA"
      "Africa/Casablanca"
    when "GN"
      "Africa/Conakry"
    when "SN"
      "Africa/Dakar"
    when "DJ"
      "Africa/Djibouti"
    when "SL"
      "Africa/Freetown"
    when "BW"
      "Africa/Gaborone"
    when "ZW"
      "Africa/Harare"
    when "ZA"
      "Africa/Johannesburg"
    when "UG"
      "Africa/Kampala"
    when "SD"
      "Africa/Khartoum"
    when "RW"
      "Africa/Kigali"
    when "NG"
      "Africa/Lagos"
    when "GA"
      "Africa/Libreville"
    when "TG"
      "Africa/Lome"
    when "AO"
      "Africa/Luanda"
    when "ZM"
      "Africa/Lusaka"
    when "GQ"
      "Africa/Malabo"
    when "MZ"
      "Africa/Maputo"
    when "LS"
      "Africa/Maseru"
    when "SZ"
      "Africa/Mbabane"
    when "SO"
      "Africa/Mogadishu"
    when "LR"
      "Africa/Monrovia"
    when "KE"
      "Africa/Nairobi"
    when "TD"
      "Africa/Ndjamena"
    when "NE"
      "Africa/Niamey"
    when "MR"
      "Africa/Nouakchott"
    when "BF"
      "Africa/Ouagadougou"
    when "ST"
      "Africa/Sao_Tome"
    when "LY"
      "Africa/Tripoli"
    when "TN"
      "Africa/Tunis"
    when "AI"
      "America/Anguilla"
    when "AG"
      "America/Antigua"
    when "AW"
      "America/Aruba"
    when "BB"
      "America/Barbados"
    when "BZ"
      "America/Belize"
    when "CO"
      "America/Bogota"
    when "VE"
      "America/Caracas"
    when "KY"
      "America/Cayman"
    when "MX"
      "America/Chihuahua"
    when "CR"
      "America/Costa_Rica"
    when "DM"
      "America/Dominica"
    when "SV"
      "America/El_Salvador"
    when "GD"
      "America/Grenada"
    when "FR"
      "Europe/Paris"
    when "GP"
      "America/Guadeloupe"
    when "GT"
      "America/Guatemala"
    when "EC"
      "America/Guayaquil"
    when "GY"
      "America/Guyana"
    when "CU"
      "America/Havana"
    when "JM"
      "America/Jamaica"
    when "BO"
      "America/La_Paz"
    when "PE"
      "America/Lima"
    when "NI"
      "America/Managua"
    when "MQ"
      "America/Martinique"
    when "AR"
      "America/Mendoza"
    when "UY"
      "America/Montevideo"
    when "MS"
      "America/Montserrat"
    when "BS"
      "America/Nassau"
    when "PA"
      "America/Panama"
    when "SR"
      "America/Paramaribo"
    when "PR"
      "America/Puerto_Rico"
    when "KN"
      "America/St_Kitts"
    when "LC"
      "America/St_Lucia"
    when "VC"
      "America/St_Vincent"
    when "HN"
      "America/Tegucigalpa"
    when "YE"
      "Asia/Aden"
    when "KZ"
      "Asia/Almaty"
    when "JO"
      "Asia/Amman"
    when "TM"
      "Asia/Ashgabat"
    when "IQ"
      "Asia/Baghdad"
    when "BH"
      "Asia/Bahrain"
    when "AZ"
      "Asia/Baku"
    when "TH"
      "Asia/Bangkok"
    when "LB"
      "Asia/Beirut"
    when "KG"
      "Asia/Bishkek"
    when "BN"
      "Asia/Brunei"
    when "IN"
      "Asia/Calcutta"
    when "MN"
      "Asia/Choibalsan"
    when "CN"
      "Asia/Chongqing"
    when "LK"
      "Asia/Colombo"
    when "BD"
      "Asia/Dhaka"
    when "AE"
      "Asia/Dubai"
    when "TJ"
      "Asia/Dushanbe"
    when "HK"
      "Asia/Hong_Kong"
    when "TR"
      "Asia/Istanbul"
    when "ID"
      "Asia/Jakarta"
    when "IL"
      "Asia/Jerusalem"
    when "AF"
      "Asia/Kabul"
    when "PK"
      "Asia/Karachi"
    when "NP"
      "Asia/Katmandu"
    when "KW"
      "Asia/Kuwait"
    when "MO"
      "Asia/Macao"
    when "PH"
      "Asia/Manila"
    when "OM"
      "Asia/Muscat"
    when "CY"
      "Asia/Nicosia"
    when "KP"
      "Asia/Pyongyang"
    when "QA"
      "Asia/Qatar"
    when "MM"
      "Asia/Rangoon"
    when "SA"
      "Asia/Riyadh"
    when "KR"
      "Asia/Seoul"
    when "SG"
      "Asia/Singapore"
    when "TW"
      "Asia/Taipei"
    when "UZ"
      "Asia/Tashkent"
    when "GE"
      "Asia/Tbilisi"
    when "BT"
      "Asia/Thimphu"
    when "JP"
      "Asia/Tokyo"
    when "LA"
      "Asia/Vientiane"
    when "AM"
      "Asia/Yerevan"
    when "PT"
      "Atlantic/Azores"
    when "BM"
      "Atlantic/Bermuda"
    when "CV"
      "Atlantic/Cape_Verde"
    when "FO"
      "Atlantic/Faeroe"
    when "IS"
      "Atlantic/Reykjavik"
    when "GS"
      "Atlantic/South_Georgia"
    when "SH"
      "Atlantic/St_Helena"
    when "BR"
      "Brazil/Acre"
    when "CL"
      "Chile/Continental"
    when "NL"
      "Europe/Amsterdam"
    when "AD"
      "Europe/Andorra"
    when "GR"
      "Europe/Athens"
    when "YU"
      "Europe/Belgrade"
    when "DE"
      "Europe/Berlin"
    when "SK"
      "Europe/Bratislava"
    when "BE"
      "Europe/Brussels"
    when "RO"
      "Europe/Bucharest"
    when "HU"
      "Europe/Budapest"
    when "DK"
      "Europe/Copenhagen"
    when "IE"
      "Europe/Dublin"
    when "GI"
      "Europe/Gibraltar"
    when "FI"
      "Europe/Helsinki"
    when "UA"
      "Europe/Kiev"
    when "SI"
      "Europe/Ljubljana"
    when "GB"
      "Europe/London"
    when "LU"
      "Europe/Luxembourg"
    when "ES"
      "Europe/Madrid"
    when "MT"
      "Europe/Malta"
    when "BY"
      "Europe/Minsk"
    when "MC"
      "Europe/Monaco"
    when "RU"
      "Europe/Moscow"
    when "NO"
      "Europe/Oslo"
    when "CZ"
      "Europe/Prague"
    when "LV"
      "Europe/Riga"
    when "IT"
      "Europe/Rome"
    when "SM"
      "Europe/San_Marino"
    when "BA"
      "Europe/Sarajevo"
    when "MK"
      "Europe/Skopje"
    when "BG"
      "Europe/Sofia"
    when "SE"
      "Europe/Stockholm"
    when "EE"
      "Europe/Tallinn"
    when "AL"
      "Europe/Tirane"
    when "LI"
      "Europe/Vaduz"
    when "VA"
      "Europe/Vatican"
    when "AT"
      "Europe/Vienna"
    when "LT"
      "Europe/Vilnius"
    when "PL"
      "Europe/Warsaw"
    when "HR"
      "Europe/Zagreb"
    when "IR"
      "Asia/Tehran"
    when "NZ"
      "Pacific/Auckland"
    when "MG"
      "Indian/Antananarivo"
    when "CX"
      "Indian/Christmas"
    when "CC"
      "Indian/Cocos"
    when "KM"
      "Indian/Comoro"
    when "MV"
      "Indian/Maldives"
    when "MU"
      "Indian/Mauritius"
    when "YT"
      "Indian/Mayotte"
    when "RE"
      "Indian/Reunion"
    when "FJ"
      "Pacific/Fiji"
    when "TV"
      "Pacific/Funafuti"
    when "GU"
      "Pacific/Guam"
    when "NR"
      "Pacific/Nauru"
    when "NU"
      "Pacific/Niue"
    when "NF"
      "Pacific/Norfolk"
    when "PW"
      "Pacific/Palau"
    when "PN"
      "Pacific/Pitcairn"
    when "CK"
      "Pacific/Rarotonga"
    when "WS"
      "Pacific/Samoa"
    when "KI"
      "Pacific/Tarawa"
    when "TO"
      "Pacific/Tongatapu"
    when "WF"
      "Pacific/Wallis"
    when "TZ"
      "Africa/Dar_es_Salaam"
    when "VN"
      "Asia/Phnom_Penh"
    when "KH"
      "Asia/Phnom_Penh"
    when "CM"
      "Africa/Lagos"
    when "DO"
      "America/Santo_Domingo"
    when "TL"
      "Asia/Jakarta"
    when "ET"
      "Africa/Addis_Ababa"
    when "FX"
      "Europe/Paris"
    when "GL"
      "America/Godthab"
    when "HT"
      "America/Port-au-Prince"
    when "CH"
      "Europe/Zurich"
    when "AN"
      "America/Curacao"
    when "BJ"
      "Africa/Porto-Novo"
    when "EH"
      "Africa/El_Aaiun"
    when "FK"
      "Atlantic/Stanley"
    when "GF"
      "America/Cayenne"
    when "IO"
      "Indian/Chagos"
    when "MD"
      "Europe/Chisinau"
    when "MP"
      "Pacific/Saipan"
    when "MW"
      "Africa/Blantyre"
    when "NA"
      "Africa/Windhoek"
    when "NC"
      "Pacific/Noumea"
    when "PG"
      "Pacific/Port_Moresby"
    when "PM"
      "America/Miquelon"
    when "PS"
      "Asia/Gaza"
    when "PY"
      "America/Asuncion"
    when "SB"
      "Pacific/Guadalcanal"
    when "SC"
      "Indian/Mahe"
    when "SJ"
      "Arctic/Longyearbyen"
    when "SY"
      "Asia/Damascus"
    when "TC"
      "America/Grand_Turk"
    when "TF"
      "Indian/Kerguelen"
    when "TK"
      "Pacific/Fakaofo"
    when "TT"
      "America/Port_of_Spain"
    when "VG"
      "America/Tortola"
    when "VI"
      "America/St_Thomas"
    when "VU"
      "Pacific/Efate"
    when "RS"
      "Europe/Belgrade"
    when "ME"
      "Europe/Podgorica"
    when "AX"
      "Europe/Mariehamn"
    when "GG"
      "Europe/Guernsey"
    when "IM"
      "Europe/Isle_of_Man"
    when "JE"
      "Europe/Jersey"
    when "BL"
      "America/St_Barthelemy"
    when "MF"
      "America/Marigot"
    end
  end  

end
